[package]
name = "_03_common_concept"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "variable"
path = "src/variable.rs"

[dependencies]
